char _putchar(char);
int _isupper(int c);
int _isdigit(int num);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int a);
void print_diagonal(int a);
void print_square(int a);
void print_triangle(int a);
