char *_strcat(char *fir, char *sec);
char *_strncat(char *fir, char *sec, int n);
char *_strncpy(char *fir, char *sec, int n);
int *_strcmp(char *fir, char *sec);
void reverse_array(int *a, int n);
char *string_toupper(char *str);
char *cap_string(char *s);
char *leet(char *str);
char *rot13(char *);
void print_number(int n);
char *infinite_add(char *n1, char *n2, char *r, int size_r);
void print_buffer(char *b, int size);
